# Generated by Django 5.2.6 on 2025-09-14 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cuota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tipo_usuario',
        ),
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='api.rol'),
        ),
    ]
