# Generated by Django 5.2.6 on 2025-09-24 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_tipo_usuario_user_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=20, verbose_name='Cédula de Identidad')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_evento', models.CharField(choices=[('cumpleanos', 'Cumpleaños'), ('reunion', 'Reunión'), ('fiesta', 'Fiesta'), ('otro', 'Otro')], default='reunion', max_length=20)),
                ('descripcion_evento', models.TextField(blank=True, null=True)),
                ('fecha_evento', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('numero_invitados', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invitado',
                'verbose_name_plural': 'Invitados',
                'ordering': ['-creado_en'],
            },
        ),
    ]
