# Generated by Django 5.2.6 on 2025-09-27 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_invitado'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acceso', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('estado', models.CharField(choices=[('exitoso', 'Exitoso'), ('fallido', 'Fallido'), ('dudoso', 'Dudoso')], default='exitoso', max_length=10)),
                ('confianza', models.FloatField(blank=True, help_text='Nivel de confianza del reconocimiento (0-1)', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('imagen_captura', models.ImageField(blank=True, null=True, upload_to='accesos/')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Acceso',
                'verbose_name_plural': 'Registros de Acceso',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RostroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.TextField(help_text='Vector de características faciales en formato JSON')),
                ('imagen_referencia', models.ImageField(blank=True, null=True, upload_to='rostros/')),
                ('esta_activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rostro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rostro de Usuario',
                'verbose_name_plural': 'Rostros de Usuario',
            },
        ),
    ]
