# Generated by Django 5.2.6 on 2025-09-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_registroacceso_rostrousuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionReconocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('valor', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Reconocimiento',
                'verbose_name_plural': 'Configuraciones de Reconocimiento',
            },
        ),
        migrations.AddField(
            model_name='rostrousuario',
            name='confianza_promedio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='rostrousuario',
            name='total_accesos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rostrousuario',
            name='ultimo_acceso',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
