# Generated by Django 5.2.6 on 2025-09-26 19:13

import avisos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0004_invitado"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Aviso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=160)),
                ("contenido", models.TextField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("PENDIENTE", "Pendiente"),
                            ("PUBLICADO", "Publicado"),
                            ("ARCHIVADO", "Archivado"),
                            ("RECHAZADO", "Rechazado"),
                        ],
                        default="BORRADOR",
                        max_length=12,
                    ),
                ),
                ("requiere_aprobacion", models.BooleanField(default=False)),
                (
                    "visibilidad",
                    models.CharField(
                        choices=[
                            ("TODOS", "Todos"),
                            ("SOLO_RESIDENTES", "Solo residentes"),
                            ("SOLO_ADMIN", "Solo administradores"),
                            ("POR_UNIDAD", "Por unidad habitacional"),
                        ],
                        default="TODOS",
                        max_length=20,
                    ),
                ),
                ("fecha_publicacion", models.DateTimeField(blank=True, null=True)),
                ("vence_en", models.DateTimeField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="avisos_autor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unidades_destino",
                    models.ManyToManyField(
                        blank=True, related_name="avisos", to="api.unidadhabitacional"
                    ),
                ),
            ],
            options={
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="Adjunto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(upload_to=avisos.models.adjunto_upload_to),
                ),
                ("nombre_original", models.CharField(blank=True, max_length=255)),
                ("tipo_mime", models.CharField(blank=True, max_length=100)),
                ("tamano_bytes", models.BigIntegerField(default=0)),
                ("subido_en", models.DateTimeField(auto_now_add=True)),
                (
                    "aviso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjuntos",
                        to="avisos.aviso",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="aviso",
            index=models.Index(
                fields=["estado", "fecha_publicacion"],
                name="avisos_avis_estado_15cfb9_idx",
            ),
        ),
    ]
