# Generated by Django 5.2.6 on 2025-09-18 19:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('rol', models.CharField(blank=True, max_length=64)),
                ('accion', models.CharField(max_length=128)),
                ('entidad', models.CharField(blank=True, max_length=128)),
                ('entidad_id', models.CharField(blank=True, max_length=64)),
                ('metodo', models.CharField(blank=True, max_length=8)),
                ('ruta', models.CharField(blank=True, max_length=256)),
                ('status', models.PositiveIntegerField(default=0)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('hash_prev', models.CharField(blank=True, max_length=64)),
                ('hash_actual', models.CharField(blank=True, max_length=64)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_bitacora', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['fecha'], name='bitacora_bi_fecha_b672a3_idx'), models.Index(fields=['accion'], name='bitacora_bi_accion_c78828_idx'), models.Index(fields=['entidad', 'entidad_id'], name='bitacora_bi_entidad_dabeb0_idx')],
            },
        ),
    ]
