# Generated by Django 5.2.6 on 2025-09-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bitacora", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bitacora",
            options={
                "ordering": ["-fecha"],
                "verbose_name": "Bitácora",
                "verbose_name_plural": "Bitácoras",
            },
        ),
        migrations.RemoveIndex(
            model_name="bitacora",
            name="bitacora_bi_fecha_b672a3_idx",
        ),
        migrations.RemoveIndex(
            model_name="bitacora",
            name="bitacora_bi_accion_c78828_idx",
        ),
        migrations.RemoveIndex(
            model_name="bitacora",
            name="bitacora_bi_entidad_dabeb0_idx",
        ),
        migrations.RemoveField(
            model_name="bitacora",
            name="hash_actual",
        ),
        migrations.RemoveField(
            model_name="bitacora",
            name="hash_prev",
        ),
        migrations.RemoveField(
            model_name="bitacora",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="bitacora",
            name="request_id",
        ),
        migrations.AddField(
            model_name="bitacora",
            name="extra",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bitacora",
            name="accion",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("CREATE", "Create"),
                    ("READ", "Read"),
                    ("UPDATE", "Update"),
                    ("DELETE", "Delete"),
                ],
                default="READ",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="bitacora",
            name="entidad",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="bitacora",
            name="entidad_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="bitacora",
            name="metodo",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="bitacora",
            name="rol",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="bitacora",
            name="ruta",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="bitacora",
            name="status",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="bitacora",
            name="user_agent",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bitacora",
            name="usuario",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
